import type { AthUiSchema } from './types'

export const defaultSchema: AthUiSchema = {
  schemaVersion: 'ath-ui-schema-0.2',
  sections: [
    {
      id: 'project',
      title: 'Project',
      groups: [
        {
          id: 'paths',
          title: 'Paths',
          items: ['Output.SubDir', 'Output.DestDir', '_athui.MeshCmd', '_athui.GnuplotPath'],
        },
      ],
    },
    {
      id: 'geometry',
      title: 'Waveguide Geometry',
      groups: [
        {
          id: 'profile',
          title: 'Profile',
          items: [
            'HornGeometry',
            'Throat.Profile',
            'Throat.Diameter',
            'Throat.Angle',
            'Coverage.Angle',
            'Length',
            'OS.k',
            'Term.s',
            'Term.q',
            'Term.n',
            'CircArc.Radius',
            'CircArc.TermAngle',
          ],
        },
        {
          id: 'throatExt',
          title: 'Throat & Slot',
          items: ['Throat.Ext.Length', 'Throat.Ext.Angle', 'Slot.Length', 'Rot'],
        },
        {
          id: 'guidingCurve',
          title: 'Guiding Curve',
          items: ['GCurve.Type', 'GCurve.Dist', 'GCurve.Width', 'GCurve.AspectRatio', 'GCurve.SE.n', 'GCurve.SF', 'GCurve.Rot'],
        },
        {
          id: 'rectangularThroat',
          title: 'Rectangular Throat',
          items: [
            'Horn.Adapter.Width',
            'Horn.Adapter.Height',
            'Horn.Adapter.Length',
            'Horn.Adapter.k',
            'Horn.Adapter.Segments',
            '_athui.HornParts',
          ],
        },
      ],
    },
    {
      id: 'shape',
      title: 'Mouth Shaping',
      groups: [
        {
          id: 'morph',
          title: 'Morph',
          items: [
            'Morph.TargetShape',
            'Morph.TargetWidth',
            'Morph.TargetHeight',
            'Morph.CornerRadius',
            'Morph.FixedPart',
            'Morph.Rate',
            'Morph.AllowShrinkage',
          ],
        },
        {
          id: 'termination',
          title: 'Mouth Termination',
          items: ['_athui.MouthTermination', '_athui.RollbackAngleDeg'],
        },
      ],
    },
    {
      id: 'mesh',
      title: 'Mesh',
      groups: [
        {
          id: 'gen',
          title: 'Resolution',
          items: [
            '_athui.MeshQuality',
            'Mesh.Quadrants',
            'Mesh.AngularSegments',
            'Mesh.LengthSegments',
            'Mesh.CornerSegments',
            'Mesh.ThroatSegments',
            'Mesh.ThroatResolution',
            'Mesh.MouthResolution',
          ],
        },
        {
          id: 'subdomains',
          title: 'Subdomains',
          items: ['Mesh.SubdomainSlices', 'Mesh.InterfaceOffset', 'Mesh.InterfaceDraw'],
        },
        {
          id: 'freeStanding',
          title: 'Free Standing',
          items: ['Mesh.RearShape', 'Mesh.WallThickness', 'Mesh.RearResolution', 'Mesh.Enclosure'],
        },
      ],
    },
    {
      id: 'abec',
      title: 'BEM / ABEC',
      groups: [
        {
          id: 'sim',
          title: 'Simulation',
          items: ['ABEC.SimType', 'ABEC.SimProfile', 'ABEC.f1', 'ABEC.f2', 'ABEC.NumFrequencies', 'ABEC.Abscissa', 'ABEC.MeshFrequency'],
        },
        {
          id: 'source',
          title: 'Source',
          items: ['Source.Shape', 'Source.Radius', 'Source.Curv', 'Source.Velocity', 'Source.Contours'],
        },
        {
          id: 'le',
          title: 'Driver Model (LE)',
          items: ['LE', 'LE.System', 'LE.Driver', 'LE.Voltage'],
        },
        {
          id: 'observations',
          title: 'Observations',
          items: ['ABEC.Polars:SPL'],
        },
      ],
    },
    {
      id: 'output',
      title: 'Outputs',
      groups: [
        {
          id: 'files',
          title: 'Generated Files',
          items: ['Output.STL', 'Output.MSH', 'Output.ABECProject', 'GridExport:SlicesProfiles'],
        },
        {
          id: 'report',
          title: 'Report',
          items: ['Report'],
        },
      ],
    },
  ],
  items: {
    '_athui.MeshCmd': {
      key: '_athui.MeshCmd',
      label: 'Mesh Command',
      valueType: 's',
      description: 'Optional. Command used by Ath to invoke Gmsh.',
      default: '',
      ui: {
        widget: 'text',
        placeholder: 'gmsh.exe %f -',
        help: 'Optional. Example: "C:\\\\path\\\\to\\\\gmsh.exe %f -". If blank, the server tries to auto-detect gmsh (or use the local install from npm run setup:gmsh).',
      },
    },
    '_athui.GnuplotPath': {
      key: '_athui.GnuplotPath',
      label: 'Gnuplot Path',
      valueType: 's',
      description: 'Optional. Used for report generation.',
      default: '',
      ui: {
        widget: 'text',
        placeholder: 'C:\\Program Files\\gnuplot\\bin\\gnuplot.exe',
        help: 'Optional. If set, the server writes GnuplotPath into ath.cfg.',
      },
    },
    'Output.SubDir': {
      key: 'Output.SubDir',
      label: 'Output Subdirectory',
      valueType: 's',
      description: 'Optional subdirectory under OutputRootDir.',
      default: '',
      ui: {
        widget: 'text',
        placeholder: 'e.g. demos',
        help: 'Optional. Organizes outputs under OutputRootDir. Leave blank to write directly to the project output root.',
      },
    },
    'Output.DestDir': {
      key: 'Output.DestDir',
      label: 'Output Destination Directory',
      valueType: 's',
      description: 'Optional override for OutputRootDir (advanced).',
      default: '',
      ui: {
        widget: 'folder',
        placeholder: 'Optional (browser cannot read absolute paths)',
        help: 'Optional. Overrides the output root directory from ath.cfg. Note: files written outside the sandbox will not show up in the Studio file list.',
        advanced: true,
      },
    },
    HornGeometry: {
      key: 'HornGeometry',
      label: 'Horn Geometry',
      valueType: 'i',
      description: 'Axisymmetric (circular) or rectangular throat geometry.',
      default: 1,
      ui: {
        widget: 'select',
        help: 'Use Rectangular for asymmetric horns with separate H/V profile control.',
        options: [
          { value: 1, label: 'Axisymmetric (circular throat)' },
          { value: 2, label: 'Rectangular throat' },
        ],
      },
    },
    'Horn.Adapter.Width': {
      key: 'Horn.Adapter.Width',
      label: 'Adapter Width',
      valueType: 'f',
      units: 'mm',
      description: 'Width of the rectangular throat adapter.',
      default: 28,
      visibleWhen: [{ key: 'HornGeometry', op: 'eq', value: 2 }],
      ui: { widget: 'number', placeholder: '28', help: 'Horizontal dimension of throat opening.' },
    },
    'Horn.Adapter.Height': {
      key: 'Horn.Adapter.Height',
      label: 'Adapter Height',
      valueType: 'f',
      units: 'mm',
      description: 'Height of the rectangular throat adapter.',
      default: 121.5,
      visibleWhen: [{ key: 'HornGeometry', op: 'eq', value: 2 }],
      ui: { widget: 'number', placeholder: '121.5', help: 'Vertical dimension of throat opening.' },
    },
    'Horn.Adapter.k': {
      key: 'Horn.Adapter.k',
      label: 'Adapter k',
      valueType: 'f',
      description: 'Shape parameter for adapter transition.',
      default: 0,
      visibleWhen: [{ key: 'HornGeometry', op: 'eq', value: 2 }],
      ui: { widget: 'number', placeholder: '0', help: 'Controls the throat-to-horn transition shape. 0 = sharp, higher = smoother.' },
    },
    'Horn.Adapter.Length': {
      key: 'Horn.Adapter.Length',
      label: 'Adapter Length',
      valueType: 'f',
      units: 'mm',
      description: 'Axial length of the circular-to-rectangular throat adapter.',
      default: 0,
      visibleWhen: [{ key: 'HornGeometry', op: 'eq', value: 2 }],
      ui: {
        widget: 'number',
        placeholder: '0',
        help: 'Set 0 for a rectangular throat at the horn start. Use >0 to transition from a circular throat to the rectangular horn.',
      },
    },
    'Horn.Adapter.Segments': {
      key: 'Horn.Adapter.Segments',
      label: 'Adapter Segments',
      valueType: 'i',
      description: 'Number of segments for adapter.',
      default: 0,
      visibleWhen: [{ key: 'HornGeometry', op: 'eq', value: 2 }],
      ui: { widget: 'number', placeholder: '0', help: 'Number of mesh segments in the adapter section.' },
    },
    '_athui.HornParts': {
      key: '_athui.HornParts',
      label: 'Horn Parts',
      valueType: '{}',
      description: 'Define H and V profiles for each horn section.',
      visibleWhen: [{ key: 'HornGeometry', op: 'eq', value: 2 }],
      ui: { widget: 'hornParts' },
    },
    'Throat.Profile': {
      key: 'Throat.Profile',
      label: 'Profile Type',
      valueType: 'i',
      description: 'Selects the waveguide profile family.',
      default: 1,
      required: true,
      visibleWhen: [{ key: 'HornGeometry', op: 'neq', value: 2 }],
      ui: {
        widget: 'select',
        help: 'OS-SE is the main constant-directivity profile. Circular arc is a simple arc-based profile.',
        options: [
          { value: 1, label: 'OS-SE (Oblate Spheroidal + Superellipse termination)' },
          { value: 3, label: 'Circular arc' },
        ],
      },
    },
    'Throat.Diameter': {
      key: 'Throat.Diameter',
      label: 'Throat Diameter',
      valueType: 'f',
      units: 'mm',
      description: 'Diameter at the throat.',
      default: 25.4,
      visibleWhen: [{ key: 'HornGeometry', op: 'neq', value: 2 }],
      ui: { widget: 'number', placeholder: '25.4', help: 'Typical: 25.4 mm (1") or 34 mm (1.4").' },
    },
    'Throat.Angle': {
      key: 'Throat.Angle',
      label: 'Throat Opening Half-Angle',
      valueType: 'ex',
      units: 'deg',
      description: 'Half of the included opening angle at the throat.',
      default: '7',
      visibleWhen: [{ key: 'HornGeometry', op: 'neq', value: 2 }],
      ui: {
        widget: 'text',
        placeholder: '7',
        help: 'Typical: 5–12. Use expressions if needed (e.g. 7 + 2*sin(p)^2).',
      },
    },
    'Coverage.Angle': {
      key: 'Coverage.Angle',
      label: 'Coverage Half-Angle',
      valueType: 'ex',
      units: 'deg',
      description: 'Nominal coverage half-angle (e.g. 45 = 90° coverage).',
      default: '45',
      visibleWhen: [{ key: 'GCurve.Type', op: 'undefined' }],
      ui: {
        widget: 'text',
        placeholder: '45',
        help: 'Typical: 30-60. Enter the half-angle directly in degrees.',
      },
    },
    Length: {
      key: 'Length',
      label: 'Length',
      valueType: 'ex',
      units: 'mm',
      description: 'Nominal axial length (depth) of the device. Mandatory.',
      required: true,
      default: '100',
      ui: { widget: 'text', placeholder: '100', help: 'Start with 80–160 mm. Mouth size results from length + coverage.' },
    },
    'OS.k': {
      key: 'OS.k',
      label: 'OS k',
      valueType: 'ex',
      description: 'OS-SE parameter k (k=0 approximates conical).',
      default: '1',
      visibleWhen: [{ key: 'Throat.Profile', op: 'eq', value: 1 }],
      ui: { widget: 'text', placeholder: '1', help: 'Typical: 0–1. 1 = OS-SE default, 0 = conical-like.', advanced: true },
    },
    'Term.s': {
      key: 'Term.s',
      label: 'Termination s',
      valueType: 'ex',
      description: 'OS-SE termination parameter s.',
      default: '0.5',
      visibleWhen: [{ key: 'Throat.Profile', op: 'eq', value: 1 }],
      ui: { widget: 'text', placeholder: '0.5', help: 'Typical: 0.4–0.8.' },
    },
    'Term.q': {
      key: 'Term.q',
      label: 'Termination q',
      valueType: 'ex',
      description: 'OS-SE termination parameter q.',
      default: '0.996',
      visibleWhen: [{ key: 'Throat.Profile', op: 'eq', value: 1 }],
      ui: { widget: 'text', placeholder: '0.996', help: 'Typical: 0.99–0.999.' },
    },
    'Term.n': {
      key: 'Term.n',
      label: 'Termination n',
      valueType: 'ex',
      description: 'OS-SE termination parameter n.',
      default: '4.0',
      visibleWhen: [{ key: 'Throat.Profile', op: 'eq', value: 1 }],
      ui: { widget: 'text', placeholder: '4.0', help: 'Typical: 2–8.' },
    },
    'CircArc.Radius': {
      key: 'CircArc.Radius',
      label: 'Arc Radius',
      valueType: 'ex',
      units: 'mm',
      description: 'Circular arc radius (alternative to TermAngle).',
      visibleWhen: [{ key: 'Throat.Profile', op: 'eq', value: 3 }],
      ui: { widget: 'text', placeholder: '100', help: 'Only for Circular arc profile. Set either Radius or TermAngle.', advanced: true },
    },
    'CircArc.TermAngle': {
      key: 'CircArc.TermAngle',
      label: 'Arc Terminal Angle',
      valueType: 'ex',
      units: 'deg',
      description: 'Mouth terminal angle for the circular arc profile.',
      default: '1',
      visibleWhen: [{ key: 'Throat.Profile', op: 'eq', value: 3 }],
      ui: { widget: 'text', placeholder: '1', help: 'Only for Circular arc profile. Set either Radius or TermAngle.', advanced: true },
    },
    'Throat.Ext.Length': {
      key: 'Throat.Ext.Length',
      label: 'Throat Extension Length',
      valueType: 'f',
      units: 'mm',
      description: 'Optional conical throat extension length.',
      default: 0,
      ui: { widget: 'number', placeholder: '0', help: 'Typical: 0–30. Use 0 to disable.', advanced: true },
    },
    'Throat.Ext.Angle': {
      key: 'Throat.Ext.Angle',
      label: 'Throat Extension Half-Angle',
      valueType: 'f',
      units: 'deg',
      description: 'Optional conical throat extension angle (half-angle).',
      default: 0,
      ui: { widget: 'number', placeholder: '0', help: 'Typical: 0–15. Use 0 to disable.', advanced: true },
    },
    'Slot.Length': {
      key: 'Slot.Length',
      label: 'Slot Length',
      valueType: 'ex',
      units: 'mm',
      description: 'Initial straight segment length.',
      default: '0',
      ui: { widget: 'text', placeholder: '0', help: 'Use 0 for no slot. Typical: 0–20.', advanced: true },
    },
    Rot: {
      key: 'Rot',
      label: 'Profile Rotation',
      valueType: 'ex',
      units: 'deg',
      description: 'Final rotation around [0, r0].',
      default: '0',
      ui: { widget: 'text', placeholder: '0', help: 'Advanced. Rotate the computed profile. Typical: 0.', advanced: true },
    },
    'GCurve.Type': {
      key: 'GCurve.Type',
      label: 'Guiding Curve Type',
      valueType: 'i',
      description: 'Enables implicit coverage definition using a guiding curve.',
      ui: {
        widget: 'select',
        help: 'Leave blank to use explicit Coverage.Angle. Set to define the mouth outline via a guiding curve.',
        options: [
          { value: 1, label: 'Superellipse' },
          { value: 2, label: 'Superformula' },
        ],
      },
    },
    'GCurve.Dist': {
      key: 'GCurve.Dist',
      label: 'Guiding Curve Distance',
      valueType: 'ex',
      description: 'Distance from throat plane: <0..1> fraction of length, >1 absolute mm.',
      default: '0.5',
      visibleWhen: [{ key: 'GCurve.Type', op: 'defined' }],
      ui: { widget: 'text', placeholder: '0.5', help: 'Typical: 0.3–0.8 (fraction of length).' },
    },
    'GCurve.Width': {
      key: 'GCurve.Width',
      label: 'Guiding Curve Width',
      valueType: 'f',
      units: 'mm',
      description: 'Absolute size along x axis.',
      default: 68,
      visibleWhen: [{ key: 'GCurve.Type', op: 'defined' }],
      ui: { widget: 'number', placeholder: '68', help: 'Start near your target mouth width.' },
    },
    'GCurve.AspectRatio': {
      key: 'GCurve.AspectRatio',
      label: 'Guiding Curve Aspect Ratio',
      valueType: 'f',
      description: 'Height/width ratio.',
      default: 1,
      visibleWhen: [{ key: 'GCurve.Type', op: 'defined' }],
      ui: { widget: 'number', placeholder: '1', help: '1 = circle. <1 = wider than tall; >1 = taller.' },
    },
    'GCurve.SE.n': {
      key: 'GCurve.SE.n',
      label: 'Superellipse Exponent (n)',
      valueType: 'f',
      description: 'Guiding superellipse exponent (>=2).',
      default: 3,
      visibleWhen: [{ key: 'GCurve.Type', op: 'eq', value: 1 }],
      ui: { widget: 'number', placeholder: '3', help: '2 = ellipse, higher = squarer.' },
    },
    'GCurve.SF': {
      key: 'GCurve.SF',
      label: 'Superformula Parameters',
      valueType: 'f[]',
      description: 'Array: a,b,m,n1,n2,n3.',
      default: [0.95, 0.82, 4, 0.8, 7, 1.9],
      visibleWhen: [{ key: 'GCurve.Type', op: 'eq', value: 2 }],
      ui: { widget: 'numberList', placeholder: '0.95,0.82,4,0.8,7,1.9', help: 'Comma-separated: a,b,m,n1,n2,n3.' },
    },
    'GCurve.Rot': {
      key: 'GCurve.Rot',
      label: 'Guiding Curve Rotation',
      valueType: 'f',
      units: 'deg',
      description: 'Anti-clockwise rotation of guiding curve.',
      default: 0,
      visibleWhen: [{ key: 'GCurve.Type', op: 'defined' }],
      ui: { widget: 'number', placeholder: '0', help: 'Typical: 0.', advanced: true },
    },
    'Morph.TargetShape': {
      key: 'Morph.TargetShape',
      label: 'Target Shape',
      valueType: 'i',
      description: 'Morphs the raw shape to a defined mouth outline.',
      default: 0,
      ui: {
        widget: 'select',
        help: 'Use this to force a rectangular or circular mouth outline.',
        options: [
          { value: 0, label: 'None (keep raw outline)' },
          { value: 1, label: 'Rectangle' },
          { value: 2, label: 'Circle' },
        ],
      },
    },
    'Morph.TargetWidth': {
      key: 'Morph.TargetWidth',
      label: 'Target Width',
      valueType: 'f',
      units: 'mm',
      description: 'Requested final mouth width (0 = keep raw).',
      default: 0,
      visibleWhen: [{ key: 'Morph.TargetShape', op: 'neq', value: 0 }],
      ui: { widget: 'number', placeholder: '0', help: 'Set to a non-zero width to force size.', advanced: true },
    },
    'Morph.TargetHeight': {
      key: 'Morph.TargetHeight',
      label: 'Target Height',
      valueType: 'f',
      units: 'mm',
      description: 'Requested final mouth height (0 = keep raw).',
      default: 0,
      visibleWhen: [{ key: 'Morph.TargetShape', op: 'neq', value: 0 }],
      ui: { widget: 'number', placeholder: '0', help: 'Set to a non-zero height to force size.', advanced: true },
    },
    'Morph.CornerRadius': {
      key: 'Morph.CornerRadius',
      label: 'Corner Radius',
      valueType: 'f',
      units: 'mm',
      description: 'Corner radius for rectangular mouth.',
      default: 35,
      visibleWhen: [{ key: 'Morph.TargetShape', op: 'eq', value: 1 }],
      ui: { widget: 'number', placeholder: '35', help: 'Typical: 10–60.', advanced: true },
    },
    'Morph.FixedPart': {
      key: 'Morph.FixedPart',
      label: 'Fixed Part',
      valueType: 'ex',
      description: 'Fraction of length kept fixed during morph (0..1).',
      default: '0',
      visibleWhen: [{ key: 'Morph.TargetShape', op: 'neq', value: 0 }],
      ui: { widget: 'text', placeholder: '0', help: 'Typical: 0–0.7.', advanced: true },
    },
    'Morph.Rate': {
      key: 'Morph.Rate',
      label: 'Morph Rate',
      valueType: 'ex',
      description: 'Controls transition speed; min 1 (lower = more rapid).',
      default: '3',
      visibleWhen: [{ key: 'Morph.TargetShape', op: 'neq', value: 0 }],
      ui: { widget: 'text', placeholder: '3', help: 'Typical: 1–6.', advanced: true },
    },
    'Morph.AllowShrinkage': {
      key: 'Morph.AllowShrinkage',
      label: 'Allow Shrinkage',
      valueType: 'b',
      description: 'Allow shrinkage during morph (0 = auto-enlarge to avoid).',
      default: false,
      visibleWhen: [{ key: 'Morph.TargetShape', op: 'neq', value: 0 }],
      ui: { widget: 'checkbox', help: 'Usually leave disabled to avoid narrowing.', advanced: true },
    },
    Rollback: {
      key: 'Rollback',
      label: 'Enable Rollback',
      valueType: 'b',
      description: 'Activates mouth rollback feature.',
      default: false,
      ui: { widget: 'checkbox', help: 'Enable for free-standing horns with a rolled-back mouth.', advanced: true },
    },
    'Rollback.StartAt': {
      key: 'Rollback.StartAt',
      label: 'Rollback Start',
      valueType: 'ex',
      description: 'Fraction of profile length where rollback starts.',
      default: '0.5',
      visibleWhen: [{ key: 'Rollback', op: 'truthy' }],
      ui: { widget: 'text', placeholder: '0.5', help: 'Typical: 0.5–0.8.', advanced: true },
    },
    'Rollback.Angle': {
      key: 'Rollback.Angle',
      label: 'Rollback Termination Angle',
      valueType: 'ex',
      units: 'deg',
      description: 'Desired wall angle relative to axis (180 = half circle total).',
      default: '180',
      visibleWhen: [{ key: 'Rollback', op: 'truthy' }],
      ui: { widget: 'text', placeholder: '180', help: 'Typical: 150–220.', advanced: true },
    },
    '_athui.MouthTermination': {
      key: '_athui.MouthTermination',
      label: 'Termination',
      valueType: 's',
      description: 'Sets mouth termination shaping.',
      default: 'none',
      ui: {
        widget: 'select',
        help: 'Rollback is no longer supported by Ath V2025-06; use R-OSSE termination instead.',
        options: [
          { value: 'none', label: 'None' },
          { value: 'r-osse', label: 'R-OSSE (rollback replacement)' },
        ],
      },
    },
    '_athui.RollbackAngleDeg': {
      key: '_athui.RollbackAngleDeg',
      label: 'Rollback Angle',
      valueType: 'f',
      units: 'deg',
      description: 'How aggressively the mouth edge rolls back.',
      default: 180,
      visibleWhen: [{ key: '_athui.MouthTermination', op: 'eq', value: 'r-osse' }],
      ui: {
        widget: 'number',
        placeholder: '180',
        help: 'Used by athui to create a rolled-back lip in the exported mesh/profile. Set to 0 to disable. Typical: 150-220 deg.',
      },
    },
    '_athui.RollbackMm': {
      key: '_athui.RollbackMm',
      label: 'Rollback Distance',
      valueType: 'f',
      units: 'mm',
      description: 'How far the mouth edge rolls back.',
      default: 15,
      visibleWhen: [{ key: '_athui.MouthTermination', op: 'eq', value: 'r-osse' }],
      ui: {
        widget: 'number',
        placeholder: '15',
        help: 'Legacy control (mm). Prefer Rollback Angle. Set to 0 to disable.',
        advanced: true,
      },
    },
    'Mesh.Quadrants': {
      key: 'Mesh.Quadrants',
      label: 'BEM Quadrants',
      valueType: 'i',
      description: 'Portion of 3D mesh used for BEM symmetry.',
      default: 1,
      ui: {
        widget: 'select',
        help: 'Affects the ABEC/BEM simulation boundary mesh (bem_mesh.*), not the horn STL/profile. 1 = quarter-space (x>=0,y>=0). 1234 = full mesh.',
        options: [
          { value: 1, label: '1 (Quadrant 1 only)' },
          { value: 12, label: '12 (Upper half: y>=0)' },
          { value: 14, label: '14 (Right half: x>=0)' },
          { value: 1234, label: '1234 (Full mesh)' },
        ],
      },
    },
    '_athui.MeshQuality': {
      key: '_athui.MeshQuality',
      label: 'Mesh Quality',
      valueType: 's',
      description: 'Preset for mesh density/resolution. Choose Custom to manually tweak mesh parameters.',
      default: 'high',
      ui: {
        widget: 'select',
        help: 'Low is fastest; Ultra is slowest/highest detail. Custom shows the mesh controls.',
        options: [
          { value: 'low', label: 'Low' },
          { value: 'medium', label: 'Medium' },
          { value: 'high', label: 'High' },
          { value: 'ultra', label: 'Ultra' },
          { value: 'custom', label: 'Custom' },
        ],
      },
    },
    'Mesh.AngularSegments': {
      key: 'Mesh.AngularSegments',
      label: 'Angular Segments',
      valueType: 'i',
      description: 'Total number of profiles around the waveguide.',
      default: 64,
      ui: { widget: 'number', placeholder: '64', help: 'Typical: 64–128. Must be multiple of 4 (auto-adjusted).' },
    },
    'Mesh.LengthSegments': {
      key: 'Mesh.LengthSegments',
      label: 'Length Segments',
      valueType: 'i',
      description: 'Number of slices along the length.',
      default: 20,
      ui: { widget: 'number', placeholder: '20', help: 'Typical: 20–60. Higher = smoother, slower.' },
    },
    'Mesh.CornerSegments': {
      key: 'Mesh.CornerSegments',
      label: 'Corner Segments',
      valueType: 'i',
      description: 'Profiles reserved for rectangle corners (Morph.TargetShape=1).',
      default: 16,
      visibleWhen: [{ key: 'Morph.TargetShape', op: 'eq', value: 1 }],
      ui: { widget: 'number', placeholder: '16', help: 'Typical: 12–32.', advanced: true },
    },
    'Mesh.ThroatSegments': {
      key: 'Mesh.ThroatSegments',
      label: 'Throat Extension Segments',
      valueType: 'i',
      description: 'Slices reserved for throat extension (Throat.Ext.*).',
      default: 6,
      ui: { widget: 'number', placeholder: '6', help: 'Typical: 4–12 when using a throat extension.', advanced: true },
    },
    'Mesh.ThroatResolution': {
      key: 'Mesh.ThroatResolution',
      label: 'Throat Resolution',
      valueType: 'f',
      units: 'mm',
      description: 'Nominal mesh resolution at z=0.',
      default: 4,
      ui: { widget: 'number', placeholder: '4', help: 'Typical: 2–6. Smaller = finer mesh.' },
    },
    'Mesh.MouthResolution': {
      key: 'Mesh.MouthResolution',
      label: 'Mouth Resolution',
      valueType: 'f',
      units: 'mm',
      description: 'Nominal mesh resolution at z=Length.',
      default: 8,
      ui: { widget: 'number', placeholder: '8', help: 'Typical: 6–15. Interpolated from throat resolution.' },
    },
    'Mesh.SubdomainSlices': {
      key: 'Mesh.SubdomainSlices',
      label: 'Subdomain Slices',
      valueType: 'i[]',
      description: 'Slice indices for subdomain interfaces (empty disables).',
      ui: { widget: 'numberList', placeholder: 'e.g. 18', help: 'Comma-separated indices. Leave blank for default; empty list disables.', advanced: true },
    },
    'Mesh.InterfaceOffset': {
      key: 'Mesh.InterfaceOffset',
      label: 'Interface Offset',
      valueType: 'f[]',
      units: 'mm',
      description: 'Forward protrusions for interfaces.',
      ui: { widget: 'numberList', placeholder: 'e.g. 5', help: 'Comma-separated, same length as SubdomainSlices.', advanced: true },
    },
    'Mesh.InterfaceDraw': {
      key: 'Mesh.InterfaceDraw',
      label: 'Interface Draw',
      valueType: 'f[]',
      units: 'mm',
      description: 'Forward-draw depths for interfaces.',
      ui: { widget: 'numberList', placeholder: 'e.g. 0', help: 'Comma-separated, same length as SubdomainSlices.', advanced: true },
    },
    'Mesh.RearShape': {
      key: 'Mesh.RearShape',
      label: 'Rear Shape',
      valueType: 'i',
      description: 'Rear side shape for free standing horn model.',
      default: 1,
      ui: {
        widget: 'select',
        help: 'Used for free-standing horns (ABEC.SimType=2).',
        options: [
          { value: 1, label: 'Full model (realistic)' },
          { value: 2, label: 'Flat disc (mathematical surface)' },
        ],
      },
    },
    'Mesh.WallThickness': {
      key: 'Mesh.WallThickness',
      label: 'Wall Thickness',
      valueType: 'f',
      units: 'mm',
      description: 'Wall thickness for free standing horn.',
      default: 5,
      ui: { widget: 'number', placeholder: '5', help: 'Typical: 3–10 (only for free standing).', advanced: true },
    },
    'Mesh.RearResolution': {
      key: 'Mesh.RearResolution',
      label: 'Rear Resolution',
      valueType: 'f',
      units: 'mm',
      description: 'Rear wall mesh resolution for free standing horn.',
      default: 10,
      ui: { widget: 'number', placeholder: '10', help: 'Typical: 8–20 (only for free standing).', advanced: true },
    },
    'Mesh.Enclosure': {
      key: 'Mesh.Enclosure',
      label: 'Enclosure',
      valueType: '{}',
      description: 'Optional enclosure definition (pre-defined or user plan).',
      default: '',
      ui: {
        widget: 'textarea',
        placeholder: '{ Spacing = 20,20,20,20 Depth = 200 }',
        help: 'Advanced. Paste the full Mesh.Enclosure object (see User Guide 6.12 / Appendix C).',
        advanced: true,
      },
    },
    'ABEC.SimType': {
      key: 'ABEC.SimType',
      label: 'Boundary Conditions',
      valueType: 'i',
      description: 'Boundary conditions for simulation.',
      default: 1,
      ui: {
        widget: 'select',
        help: 'Infinite baffle is typical for in-baffle waveguides. Free standing models the rear side too.',
        options: [
          { value: 1, label: 'Infinite baffle' },
          { value: 2, label: 'Free standing horn' },
        ],
      },
    },
    'ABEC.SimProfile': {
      key: 'ABEC.SimProfile',
      label: 'CircSym Profile',
      valueType: 'i',
      description: 'Selects a profile for Circular Symmetry mode (-1 disables).',
      default: -1,
      ui: { widget: 'number', placeholder: '-1', help: 'Set to a profile index to enable CircSym mode.', advanced: true },
    },
    'ABEC.f1': {
      key: 'ABEC.f1',
      label: 'Start Frequency',
      valueType: 'f',
      units: 'Hz',
      description: 'Low frequency limit.',
      default: 1000,
      ui: { widget: 'number', placeholder: '1000', help: 'Typical: 200–2000.' },
    },
    'ABEC.f2': {
      key: 'ABEC.f2',
      label: 'End Frequency',
      valueType: 'f',
      units: 'Hz',
      description: 'High frequency limit.',
      default: 10000,
      ui: { widget: 'number', placeholder: '10000', help: 'Typical: 10000–20000.' },
    },
    'ABEC.NumFrequencies': {
      key: 'ABEC.NumFrequencies',
      label: 'Frequency Points',
      valueType: 'i',
      description: 'Number of frequency points.',
      default: 20,
      ui: { widget: 'number', placeholder: '20', help: 'Typical: 20–100.' },
    },
    'ABEC.Abscissa': {
      key: 'ABEC.Abscissa',
      label: 'Frequency Spacing',
      valueType: 'i',
      description: 'Spacing of frequency points.',
      default: 1,
      ui: {
        widget: 'select',
        help: 'Logarithmic is typical for wide ranges.',
        options: [
          { value: 1, label: 'Logarithmic' },
          { value: 2, label: 'Linear' },
        ],
      },
    },
    'ABEC.MeshFrequency': {
      key: 'ABEC.MeshFrequency',
      label: 'Mesh Frequency',
      valueType: 'f',
      units: 'Hz',
      description: 'ABEC mesh frequency (avoid re-meshing by using fine Mesh.*Resolution).',
      default: 1000,
      ui: { widget: 'number', placeholder: '1000', help: 'Typical: same as f1. CircSym: 30000+.', advanced: true },
    },
    'Source.Shape': {
      key: 'Source.Shape',
      label: 'Source Shape',
      valueType: 'i',
      description: 'Driving wavefront shape at the throat.',
      default: 1,
      ui: {
        widget: 'select',
        help: 'Spherical cap is typical for compression drivers.',
        options: [
          { value: 1, label: 'Spherical cap' },
          { value: 2, label: 'Flat disc' },
        ],
      },
    },
    'Source.Radius': {
      key: 'Source.Radius',
      label: 'Source Radius',
      valueType: 'f',
      units: 'mm',
      description: 'Radius of driving spherical cap (-1 auto).',
      default: -1,
      visibleWhen: [{ key: 'Source.Shape', op: 'eq', value: 1 }],
      ui: { widget: 'number', placeholder: '-1', help: '-1 = auto match throat angle.', advanced: true },
    },
    'Source.Curv': {
      key: 'Source.Curv',
      label: 'Source Curvature',
      valueType: 'i',
      description: 'Curvature of spherical cap: 1 convex, -1 concave, 0 auto.',
      default: 0,
      visibleWhen: [{ key: 'Source.Shape', op: 'eq', value: 1 }],
      ui: { widget: 'number', placeholder: '0', help: '0 = automatic.', advanced: true },
    },
    'Source.Velocity': {
      key: 'Source.Velocity',
      label: 'Velocity Direction',
      valueType: 'i',
      description: 'Velocity direction of driving elements.',
      default: 1,
      ui: {
        widget: 'select',
        help: 'Normal is typical; axial models pistonic motion along z.',
        options: [
          { value: 1, label: 'Normal to element surface' },
          { value: 2, label: 'Axial (pistonic along z)' },
        ],
      },
    },
    'Source.Contours': {
      key: 'Source.Contours',
      label: 'Source Contours Script',
      valueType: 'c',
      description: 'Overrides Source.* (except Velocity) when present.',
      default: '',
      ui: { widget: 'textarea', placeholder: '... ABEC source script ...', help: 'Advanced. See User Guide 6.5.', advanced: true },
    },
    LE: {
      key: 'LE',
      label: 'LE Model Script File',
      valueType: 's',
      description: 'Includes a lumped-element driver model (optional).',
      default: '',
      ui: { widget: 'text', placeholder: 'e.g. CDX1-1747.le', help: 'Optional. LE models live under Ath bin/lib/drivers.', advanced: true },
    },
    'LE.System': {
      key: 'LE.System',
      label: 'LE System Tag',
      valueType: 's',
      description: 'System section tag in LE script.',
      default: 'S1',
      visibleWhen: [{ key: 'LE', op: 'truthy' }],
      ui: { widget: 'text', placeholder: 'S1', help: 'Default: S1.', advanced: true },
    },
    'LE.Driver': {
      key: 'LE.Driver',
      label: 'LE Driver Tag',
      valueType: 's',
      description: 'Driver section tag in LE script.',
      default: 'D1',
      visibleWhen: [{ key: 'LE', op: 'truthy' }],
      ui: { widget: 'text', placeholder: 'D1', help: 'Default: D1.', advanced: true },
    },
    'LE.Voltage': {
      key: 'LE.Voltage',
      label: 'Input Voltage',
      valueType: 'f',
      units: 'Vrms',
      description: 'Input voltage for LE analysis.',
      default: 2.83,
      visibleWhen: [{ key: 'LE', op: 'truthy' }],
      ui: { widget: 'number', placeholder: '2.83', help: 'Default: 2.83 Vrms.', advanced: true },
    },
    'ABEC.Polars:SPL': {
      key: 'ABEC.Polars:SPL',
      label: 'Polars (SPL)',
      valueType: '{}',
      description: 'Polar map definition (object).',
      default: '',
      ui: {
        widget: 'textarea',
        placeholder: '{ MapAngleRange = 0,90,19 Offset = 95 }',
        help: 'Defines observation polars. Typical infinite-baffle start: { MapAngleRange = 0,90,19 Offset = 95 }. See User Guide 6.3 / 4.1.5.',
        advanced: true,
      },
    },
    'Output.STL': {
      key: 'Output.STL',
      label: 'Write STL',
      valueType: 'b',
      description: 'Generate STL output via mesh generator.',
      default: true,
      ui: { widget: 'checkbox', help: 'Requires gmsh (MeshCmd). The server can install gmsh via npm run setup:gmsh.' },
    },
    'Output.MSH': {
      key: 'Output.MSH',
      label: 'Write MSH',
      valueType: 'b',
      description: 'Generate MSH surface mesh (not BEM mesh).',
      default: false,
      ui: { widget: 'checkbox', help: 'Optional. Produces a whole waveguide surface mesh.', advanced: true },
    },
    'Output.ABECProject': {
      key: 'Output.ABECProject',
      label: 'Write ABEC Project',
      valueType: 'b',
      description: 'Generate ABEC project files.',
      default: true,
      ui: { widget: 'checkbox', help: 'Enable to generate *.abec and ABEC_* folders.' },
    },
    'GridExport:SlicesProfiles': {
      key: 'GridExport:SlicesProfiles',
      label: 'Grid Export',
      valueType: '{}',
      description: 'Export grid XYZ coordinates (Fusion 360 import).',
      default: '',
      ui: {
        widget: 'textarea',
        placeholder: '{ ExportProfiles = 1 ExportSlices = 1 }',
        help: 'Advanced. Paste a GridExport:<tag> object. See User Guide 4.1.6 / 5.',
        advanced: true,
      },
    },
    Report: {
      key: 'Report',
      label: 'Report',
      valueType: '{}',
      description: 'Configure report generation (gnuplot).',
      default: '',
      ui: {
        widget: 'textarea',
        placeholder: '{ Title = \"Demo\" NormAngle = 10 Width = 1024 Height = 768 }',
        help: 'Advanced. Paste the Report object. See User Guide 4.1.6 / 6.14.',
        advanced: true,
      },
    },
  },
}
